using System; using System.Collections.Generic; using System.IO; using System.Security.Cryptography; using System.Text; using System.Xml.Serialization;
namespace WinAuth.Cli {
 [Serializable] public class Entry { public string Id, Name, Issuer, Kind, Secret, Algorithm; public int Digits=6, Period=30; public long Counter; }
 [Serializable, XmlRoot("winauth-cli")] public class Vault {
  [XmlElement("authenticator")] public List<Entry> Entries = new List<Entry>();
  public static Vault Load(string file, string password) { if(!File.Exists(file)) return new Vault(); byte[] raw=File.ReadAllBytes(file); if(Encoding.ASCII.GetString(raw,0,Math.Min(8,raw.Length))=="WACLI001") raw=Crypt(raw,password,false); using(var ms=new MemoryStream(raw)) return (Vault)new XmlSerializer(typeof(Vault)).Deserialize(ms); }
  public void Save(string file,string password) { byte[] raw; var xs=new XmlSerializer(typeof(Vault)); using(var ms=new MemoryStream()){xs.Serialize(ms,this);raw=ms.ToArray();} if(!string.IsNullOrEmpty(password)) raw=Crypt(raw,password,true); string dir=Path.GetDirectoryName(Path.GetFullPath(file)); Directory.CreateDirectory(dir); string tmp=file+".tmp"; File.WriteAllBytes(tmp,raw); if(File.Exists(file)) File.Delete(file); File.Move(tmp,file); }
  static byte[] Crypt(byte[] input,string password,bool encrypt){ if(string.IsNullOrEmpty(password)) throw new InvalidOperationException("This vault needs --password or WINAUTH_PASSWORD"); if(encrypt){byte[] salt=Random(16),iv=Random(16),key=Key(password,salt); using(var aes=Aes.Create()){aes.Key=key;aes.IV=iv;using(var ms=new MemoryStream()){ms.Write(Encoding.ASCII.GetBytes("WACLI001"),0,8);ms.Write(salt,0,16);ms.Write(iv,0,16);using(var cs=new CryptoStream(ms,aes.CreateEncryptor(),CryptoStreamMode.Write)){cs.Write(input,0,input.Length);cs.FlushFinalBlock();}return ms.ToArray();}}} byte[] s=new byte[16],v=new byte[16];Array.Copy(input,8,s,0,16);Array.Copy(input,24,v,0,16);using(var aes=Aes.Create()){aes.Key=Key(password,s);aes.IV=v;using(var src=new MemoryStream(input,40,input.Length-40))using(var cs=new CryptoStream(src,aes.CreateDecryptor(),CryptoStreamMode.Read))using(var dst=new MemoryStream()){cs.CopyTo(dst);return dst.ToArray();}} }
  static byte[] Key(string p,byte[] s){using(var k=new Rfc2898DeriveBytes(p,s,100000))return k.GetBytes(32);} static byte[] Random(int n){byte[] b=new byte[n];using(var r=RandomNumberGenerator.Create())r.GetBytes(b);return b;}
 }
}
